version: '3'
services:
    mongo:
        image: mongo
        environment:
          - MONGO_INITDB_ROOT_USERNAME
          - MONGO_INITDB_ROOT_PASSWORD
          - MONGO_INITDB_DATABASE
          - TZ=Azia/Tokyo
        ports: 
            - 27017:27017
        volumes:
            - ./mongo/db:/mongo/db
            - ./mongo/configdb:/mongo/configdb
    app:
        build: 
          context: .
          dockerfile: docker/back/Dockerfile

        command: uwsgi --socket :8001 --module config.wsgi --py-autoreload 1
        volumes:
            - ./src:/code
        expose:
            - "8001"
        depends_on:
            - mongo
        restart: always
        stdin_open: true
    
    nginx:
        image: nginx:latest
        environment:
            TZ: 'Asia/Tokyo'
        ports:
            - 80:80
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/uwsgi:/etc/nginx/uwsgi
            - ./src/static:/var/www/static
            - ./src/media:/var/www/media
            - ./src/templates:/var/www/templates
        depends_on:
            - app